version: '2'
services:
  web:
    build: .
    ports:
     - "4000:4000"
    volumes:
     - .:/home/app
    depends_on:
     - db
  db:
    image: postgres
    volumes:
     - /talkin/db/etc/postgresql:/etc/postgresql
     - /talkin/db/var/log:/var/log/postgresql
     - /talkin/db/var/lib/postgresql:/var/lib/postgresql
    environment:
     - POSTGRES_USER=postgresql
     - POSTGRES_PASSWORD=pass
