version: '2'
services:
  web:
    build: .
    ports:
     - "80:4000"
    volumes:
     - .:/home/app
     - /home/rl1/phoenix_examples:/home/app/phoenix_examples
    depends_on:
     - db
  db:
    image: mdillon/postgis # database need to be created with postgres image
    ports:
      - "6000:5432"
    volumes:
     - /talkin/db/etc/postgresql:/etc/postgresql
     - /talkin/db/var/log:/var/log/postgresql
     - /talkin/db/var/lib/postgresql:/var/lib/postgresql
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=pass
